CREATE TABLE Prooducts
(
  Id SERIAL PRIMARY KEY,
  ProductName VARCHAR(30) NOT NULL,
  Company VARCHAR(20) NOT NULL,
  ProductCount INTEGER DEFAULT 0,
  Price NUMERIC NOT NULL
);
CREATE TABLE Cuustomers
(
  Id SERIAL PRIMARY KEY,
  FirstName VARCHAR(30) NOT NULL
);
CREATE TABLE Orderss
(
  Id SERIAL PRIMARY KEY,
  ProductId INTEGER NOT NULL REFERENCES Prooducts(Id) ON DELETE CASCADE,
  CustomersId INTEGER NOT NULL REFERENCES Cuustomers(Id) ON DELETE CASCADE,
  CreatedAt DATE NOT NULL,
  ProductCount INTEGER DEFAULT 1,
  Price NUMERIC NOT NULL 
);