CREATE TABLE Productsd
(
  Id SERIAL PRIMARY KEY,
  ProductName VARCHAR(30) NOT NULL,
  Company VARCHAR(20) NOT NULL,
  ProductCount INTEGER DEFAULT 0,
  Price NUMERIC NOT NULL
);
CREATE TABLE Cusstomers
(
  Id SERIAL PRIMARY KEY,
  FirstName VARCHAR(30) NOT NULL
);
CREATE TABLE Orrders
(
  Id SERIAL PRIMARY KEY,
  ProductId INTEGER NOT NULL REFERENCES Productsd(Id) ON DELETE CASCADE,
  CustomersId INTEGER NOT NULL REFERENCES Cusstomers(Id) ON DELETE CASCADE,
  CreatedAt DATE NOT NULL,
  ProductCount INTEGER DEFAULT 1,
  Price NUMERIC NOT NULL 
);